### ISSUE TITLE
CmdLine.concat gets it the wrong way

### ISSUE THREAD

**Issue by matthid** [vbfox/FoxSharp#6]
https://github.com/fsharp/FAKE/pull/2206/commits/61ea4631a7bb91b1f38360fd692a9b37331fd27e

Seems like the instance method as well as the module function have the wrong order...

**Comment by vbfox** [comment]
So the way they worked was the documented one but was weird.

Changed in 1.0.0 to take a `CmdLine seq` so there is no possible confusion about ordering

**Comment by matthid** [comment]
Yes it just was different than `Seq` or other modules behave
